### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by loveanao** [me2sy/MYScrcpy#5]
大佬，建议完善一个requirements.txt

**Comment by me2sy** [comment]
你好~ 很抱歉，项目之前生成过requirements，但是鉴于功能一直没稳定，有许多依赖包增增减减，想尽量给大家带来轻松简洁的架构环境，所以迟迟没有freeze出来。
这个我尽快稳定一个版本出来，或者后续采用extras_require的方式来处理。
十分感谢你的关注和建议~

**Comment by loveanao** [comment]
好的大佬，那您方便提供一下目前环境依赖的版本吗，loveanao@163.com

**Comment by me2sy** [comment]
pip install loguru adbutils pyperclip av numpy pyaudio pyflac dearpygui pygame pyvirtualcam nicegui

如果是linux系统，注意一下pyaudio pyflac 安装需要的基础包哈

**Comment by loveanao** [comment]
> pyflac
感谢，感谢
我用windows 10，正卡在 安装pyflac ，
正在排错

**Comment by loveanao** [comment]
> pip install loguru adbutils pyperclip av numpy pyaudio pyflac dearpygui pygame pyvirtualcam nicegui
> 
> 可以看pyproject.toml中的 dependencies 如果是linux系统，注意一下pyaudio pyflac 安装需要的基础包哈~

大佬，咨询一下，
我windows10环境
python 3.11.9
安装pyflac会报错

如下
`Collecting pyflac
  Using cached pyFLAC-3.0.0.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 33, in <module>
          from distutils.msvc9compiler import MSVCCompiler
      ModuleNotFoundError: No module named 'distutils.msvc9compiler'
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "E:\MyScrcpySAA\MYScrcpy\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\MyScrcpySAA\MYScrcpy\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\MyScrcpySAA\MYScrcpy\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\dist.py", line 283, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 278, in __init__
          self.finalize_options()
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\dist.py", line 635, in finalize_options
          ep(self)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\setuptools\dist.py", line 655, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 71, in add_cffi_module
          _add_c_module(dist, ffi, module_name, source, source_extension, kwds)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 109, in _add_c_module
          from cffi._shimmed_dist_utils import Extension, log, mkpath
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-l7lbm3d9\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 36, in <module>
          raise Exception("This CFFI feature requires setuptools on Python >= 3.12. Please install the setuptools package.") from ex
      Exception: This CFFI feature requires setuptools on Python >= 3.12. Please install the setuptools package.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
`

切换到3.12.5依旧。
在stackoverflow找了一圈也没找到合适的解决方案，

所以想了解下你的开发环境
和具体依赖包的版本号

**Comment by me2sy** [comment]
今天搞得有点晚了，明天我帮你看看~
下面是我目前的requirements.txt 不过有很多已经不用的包了 pyFLAC==3.0.0
[requirements.txt](https://github.com/user-attachments/files/16829635/requirements.txt)

**Comment by loveanao** [comment]
> 今天搞得有点晚了，明天我帮你看看~ 下面是我目前的requirements.txt 不过有很多已经不用的包了 pyFLAC==3.0.0 [requirements.txt](https://github.com/user-attachments/files/16829635/requirements.txt)

感觉是官方cffi官方bug ，问题一模一样

**Comment by me2sy** [comment]
> > 今天搞得有点晚了，明天我帮你看看~ 下面是我目前的requirements.txt 不过有很多已经不用的包了 pyFLAC==3.0.0 [requirements.txt](https://github.com/user-attachments/files/16829635/requirements.txt)
> 
> 感觉是官方cffi官方bug ，问题一模一样 [python-cffi/cffi#117](https://github.com/python-cffi/cffi/issues/117)
> 
> [python-cffi/cffi#120](https://github.com/python-cffi/cffi/pull/120)

现已发布到pypi

pip install **mysc**
(my-scrcpy已被占用。。。)
pyFLAC这个 我在win11 还有ubuntu24 全部安装成功了，你再试试，或者使用raw格式
近期我研究一下opus解码，不行把flac废弃掉
