### ISSUE TITLE
bug@1.5.4

### ISSUE THREAD

**Issue by loveanao** [me2sy/MYScrcpy#7]
File "E:\MYScrcpyMain\myscrcpy\gui\dpg\components\vc.py", line 95, in to_raw_texture_value
    self.u2f[:] = frame.reformat(format='rgb24').planes[0]

ValueError: could not broadcast input array from shape (6236160,) into shape (6220800,)

**Comment by me2sy** [comment]
几率较低，try except解决掉了

**Comment by loveanao** [comment]
> 几率较低，try except解决掉了

应该不是，我完整新拉工程，安装好依赖后 执行 run.py ,链接设备后就报错

Traceback (most recent call last):
  File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\device.py", line 204, in connect
    self.connect_callback(self.device, cfg)
  File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\device.py", line 367, in connect_scrcpy_callback
    self.scrcpy_callback(device, connect_configs)
  File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\window.py", line 865, in setup_session
    self.video_controller.load_frame(frame)
  File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\vc.py", line 147, in load_frame
    self._init_texture(_c, self.to_raw_texture_value(frame))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\vc.py", line 95, in to_raw_texture_value
    self.u2f[:] = frame.reformat(format='rgb24').planes[0]
    ~~~~~~~~^^^
ValueError: could not broadcast input array from shape (6236160,) into shape (6220800,)
