### ISSUE TITLE
Bug @ 1.5.5

### ISSUE THREAD

**Issue by loveanao** [me2sy/MYScrcpy#8]
应该不是，我完整新拉工程，安装好依赖后 执行 run.py ,链接设备后就报错

win10
python 3.11.9

```

Traceback (most recent call last):
File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\device.py", line 204, in connect
self.connect_callback(self.device, cfg)
File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\device.py", line 367, in connect_scrcpy_callback
self.scrcpy_callback(device, connect_configs)
File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\window.py", line 865, in setup_session
self.video_controller.load_frame(frame)
File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\vc.py", line 147, in load_frame
self._init_texture(_c, self.to_raw_texture_value(frame))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\MYScrcpyMain2\myscrcpy\gui\dpg\components\vc.py", line 95, in to_raw_texture_value
self.u2f[:] = frame.reformat(format='rgb24').planes[0]
~~~~~~~~^^^
ValueError: could not broadcast input array from shape (6236160,) into shape (6220800,)

```

**Comment by me2sy** [comment]
我这复现不出来呢 Video分辨率多少？
V: _Me2sY_ 
交流一下。。。

**Comment by me2sy** [comment]
跑下面这个, 看看结果
```python 
from myscrcpy.core import *
from adbutils import adb
sess = Session(adb.device_list()[0], VideoArgs(1366))
vf = sess.va.get_video_frame()
print(vf)
print(vf.reformat(format='rgb24').planes[0])
u2f = np.empty(vf.width * vf.height * 3, dtype=np.float32)
u2f[:] = vf.reformat(format='rgb24').planes[0]
print(u2f)
```

**Comment by loveanao** [comment]
> 我这复现不出来呢 Video分辨率多少？ V: _Me2sY_ 交流一下。。。

+了，可以删掉v了。免得麻烦，大佬可以建个群沟通

**Comment by loveanao** [comment]
> 跑下面这个, 看看结果
> 
> ```python
> from myscrcpy.core import *
> from adbutils import adb
> sess = Session(adb.device_list()[0], VideoArgs(1366))
> vf = sess.va.get_video_frame()
> print(vf)
> print(vf.reformat(format='rgb24').planes[0])
> u2f = np.empty(vf.width * vf.height * 3, dtype=np.float32)
> u2f[:] = vf.reformat(format='rgb24').planes[0]
> print(u2f)
> ```

```
E:\MYScrcpyMain2\.venv\Scripts\python.exe E:\MYScrcpyMain2\myscrcpy\run.py 
pygame 2.6.0 (SDL 2.28.4, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-09-06 23:06:49.921 | SUCCESS  | myscrcpy.core.video:main_thread:246 - Video Socket 53dfca5f Connected! h264 | Width: 768, Height: 1360
<av.VideoFrame, pts=None yuv420p 768x1360 at 0x1aee7e797e0>
<av.VideoPlane 3133440 bytes; buffer_ptr=0x1aee8663080; at 0x1aee7ea1e40>
[20. 21. 40. ... 56. 31. 30.]

```

**Comment by me2sy** [comment]
> > 我这复现不出来呢 Video分辨率多少？ V: _Me2sY_ 交流一下。。。
> 
> 都是直接git拉下来，是你工程默认配置 +v了，可以删掉v了。免得你后续被麻烦，大佬可以建个群沟通

V加错了。。。是 \_Me2sY\_ 有两个\_...
回头我研究个群

**Comment by loveanao** [comment]
> _Me2sY_

【 _Me2sY_ 】加了    ：)

**Comment by me2sy** [comment]
![mmexport1725636439454](https://github.com/user-attachments/assets/b45e73bf-8a8a-4782-a808-48e071546b3d)


> > _Me2sY_
> 
> `【 _Me2sY_ 】加了 ：) `

木收到，直接进群吧。。。

**Comment by me2sy** [comment]
Fix In 1.5.7
